window.data_attr={
"alternate_name":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"feature_type|alternate name"},
"attestation":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"spatial|present_location|attestation"},
"attested_by":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"spellings|attested by"},
"begin":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"temporal|begin"},
"begin_rule":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"temporal|begin rule"},
"begin_year":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"historical_context|part of|begin year"},
"begin_year":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"historical_context|subordinate units|begin_year"},
"child_id":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"historical_context|subordinate units|child id"},
"country_code":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"spatial|present_location|country code"},
"data_source":{"attr":"class","input_type":"","menu_content":"","valid_check_function_name":"","path":"data source"},
"end":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"temporal|end"},
"end_rule":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"temporal|end rule"},
"end_year":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"historical_context|part of|end year"},
"end_year":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"historical_context|subordinate units|end_year"},
"English":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"feature_type|English"},
"exonym_language":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"spellings|exonym language"},
"feature_type":{"attr":"class","input_type":"","menu_content":"","valid_check_function_name":"","path":"feature_type"},
"historical_context":{"attr":"class","input_type":"","menu_content":"","valid_check_function_name":"","path":"historical_context"},
"latitude":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"spatial|latitude"},
"longitude":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"spatial|longitude"},
"name":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"path"},
"note":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"spellings|note"},
"object_type":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"spatial|object_type"},
"parent_id":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"historical_context|part of|parent id"},
"part_of":{"attr":"class","input_type":"","menu_content":"","valid_check_function_name":"","path":"historical_context|part of"},
"preceded_by":{"attr":"class","input_type":"","menu_content":"","valid_check_function_name":"","path":"historical_context|preceded by"},
"present_location":{"attr":"class","input_type":"","menu_content":"","valid_check_function_name":"","path":"spatial|present_location"},
"script":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"spellings|script"},
"source":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"spatial|source"},
"source_note":{"attr":"class","input_type":"","menu_content":"","valid_check_function_name":"","path":"source note"},
"spatial":{"attr":"class","input_type":"","menu_content":"","valid_check_function_name":"","path":"spatial"},
"spellings":{"attr":"class","input_type":"","menu_content":"","valid_check_function_name":"","path":"spellings"},
"subordinate_units":{"attr":"class","input_type":"","menu_content":"","valid_check_function_name":"","path":"historical_context|subordinate units"},
"temporal":{"attr":"class","input_type":"","menu_content":"","valid_check_function_name":"","path":"temporal"},
"text":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"spatial|present_location|text"},
"transcribed":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"historical_context|part of|transcribed"},
"transcription":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"feature_type|transcription"},
"written_form":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"spellings|written form"},
"xy_type":{"attr":"value","input_type":"","menu_content":"","valid_check_function_name":"","path":"spatial|xy_type"}
}